apiVersion: apps/v1
kind: Deployment
metadata:
  name: html1-deployment
spec:
  selector:
    matchLabels:
      app: html1
  replicas: 2
  template:
    metadata:
      labels:
        app: html1
    spec:
      containers:
      - name: html1
        image: vnom1985/html_vinod
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "200m"
