apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins1-deployment
spec:
  selector:
    matchLabels:
      app: jenkins1
  replicas: 2
  template:
    metadata:
      labels:
        app: jenkins1
    spec:
      containers:
      - name: jenkins1
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "200m"
