---
apiVersion: v1
kind: Pod
metadata:
  name: jenkinstest
  labels:
    app: jenkinstest
spec:
  containers:
    - name: jenkinstest
      image: jenkins/jenkins:lts
      ports:
        - containerPort: 8080