piVersion: v1
kind: Service
metadata:
  labels:
    app: service3
  name: service3
spec:
  ports:
  - name: httpd3
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30085
  selector:
    app: httpd3
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd3
  name: httpd3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd3
  template:
    metadata:
      labels:
        app: httpd3
    spec:
      containers:
      - image: vnom1985/petshop1
        name: httpd3
        ports:
        - containerPort: 80